import { createNode } from '../model/nodeSchema.js';
import { linearToGraph } from '../transformer/linearToGraph.js';
import { matchVisit } from './matchers/visit.js';
import { matchClick } from './matchers/click.js';
import { matchType } from './matchers/type.js';
import { matchAssert } from './matchers/assert.js';

const MATCHERS = [matchVisit, matchClick, matchType, matchAssert];

/**
 * Parse Cypress test code generated by generate.js back into a Flow.
 * Non-Cypress lines (describe/it/comments/{/}) are silently ignored.
 *
 * @param {string} code   - Cypress test source
 * @param {object} meta   - { name?, baseUrl? } for the reconstructed flow
 * @returns {Flow}
 */
export function parse(code, meta = {}) {
  const nodes = [];

  for (const rawLine of code.split('\n')) {
    const line = rawLine.trim();
    if (!line) continue;

    for (const matcher of MATCHERS) {
      const result = matcher(line);
      if (result) {
        nodes.push(createNode(result.type, { params: result.params }));
        break;
      }
    }
  }

  return linearToGraph(nodes, meta);
}
