import { useMemo, useState } from 'react';
import { useFlowStore } from '../../core/state/useFlowStore.js';
import { generate } from '../../core/codegen/generate.js';
import { parse } from '../../core/parser/parse.js';

export default function CodePanel() {
  const flow = useFlowStore((s) => s.flow);
  const [copied, setCopied]       = useState(false);
  const [importMode, setImportMode] = useState(null); // null | 'json' | 'cypress'
  const [importText, setImportText] = useState('');
  const [importError, setImportError] = useState('');

  const code = useMemo(() => {
    try { return generate(flow); }
    catch { return '// Add nodes to the canvas to generate code.'; }
  }, [flow]);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {}
  };

  const exportJson = () => {
    const blob = new Blob([JSON.stringify(flow, null, 2)], { type: 'application/json' });
    const url  = URL.createObjectURL(blob);
    const a    = Object.assign(document.createElement('a'), { href: url, download: `${flow.name || 'flow'}.json` });
    a.click();
    URL.revokeObjectURL(url);
  };

  const openImport = (mode) => {
    setImportMode(mode);
    setImportText('');
    setImportError('');
  };

  const cancelImport = () => {
    setImportMode(null);
    setImportText('');
    setImportError('');
  };

  const runImport = () => {
    setImportError('');
    try {
      let loaded;
      if (importMode === 'json') {
        loaded = JSON.parse(importText);
      } else {
        loaded = parse(importText, { name: flow.name, baseUrl: flow.baseUrl });
      }
      useFlowStore.getState().loadFlow(loaded);
      cancelImport();
    } catch (e) {
      setImportError(e.message);
    }
  };

  return (
    <section className="codepanel">
      <header className="codepanel-head">
        <h3 className="panel-title">Cypress code</h3>
        <div className="codepanel-actions">
          <button onClick={copy} className="copy-btn">{copied ? 'Copied!' : 'Copy'}</button>
          <button onClick={exportJson} className="copy-btn">Export JSON</button>
          <button onClick={() => openImport('json')}    className={`copy-btn ${importMode === 'json'    ? 'active' : ''}`}>Import JSON</button>
          <button onClick={() => openImport('cypress')} className={`copy-btn ${importMode === 'cypress' ? 'active' : ''}`}>Import Cypress</button>
        </div>
      </header>

      {importMode && (
        <div className="import-panel">
          <p className="import-hint">
            {importMode === 'json'
              ? 'Paste a flow JSON file to load it.'
              : 'Paste Cypress code generated by this tool to reconstruct the flow.'}
          </p>
          <textarea
            className="import-textarea"
            value={importText}
            onChange={(e) => { setImportText(e.target.value); setImportError(''); }}
            placeholder={importMode === 'json' ? '{ "version": "1.0", ... }' : 'describe("My Flow", () => { ... });'}
            spellCheck={false}
          />
          {importError && <p className="import-error">{importError}</p>}
          <div className="import-footer">
            <button onClick={runImport} className="copy-btn" disabled={!importText.trim()}>Load</button>
            <button onClick={cancelImport} className="copy-btn">Cancel</button>
          </div>
        </div>
      )}

      <pre className="codepanel-pre"><code>{code}</code></pre>
    </section>
  );
}
