import { graphToLinear } from '../transformer/graphToLinear.js';
import { emitVisit } from './emitters/visit.js';
import { emitClick } from './emitters/click.js';
import { emitType } from './emitters/type.js';
import { emitAssert } from './emitters/assert.js';

const EMITTERS = {
  visit: emitVisit,
  click: emitClick,
  type: emitType,
  assert: emitAssert,
};

const PAD = '    '; // 4 spaces — 2 (describe) + 2 (it)

export function generate(flow) {
  const nodes = graphToLinear(flow);
  const name = flow.name || 'Untitled Flow';

  const lines = [
    `// Generated by Cypress Visual Test Builder`,
    `// Flow: ${name}`,
  ];
  if (flow.baseUrl) lines.push(`// baseUrl: ${flow.baseUrl}`);
  lines.push('');

  lines.push(`describe(${JSON.stringify(name)}, () => {`);
  lines.push(`  it("should complete the flow", () => {`);

  for (const node of nodes) {
    const emitter = EMITTERS[node.type];
    if (!emitter) throw new Error(`No emitter for node type "${node.type}"`);
    lines.push(PAD + emitter(node, flow));
  }

  lines.push(`  });`);
  lines.push(`});`);

  return lines.join('\n');
}
